# Using Array

# 1. Create and accessing
### Array{Typeof, no. of dimension}
### One dimension array 
One dimension array be will set as vector or column array

In [22]:
xr1=[1 2 3 4 5]

1×5 Array{Int64,2}:
 1  2  3  4  5

In [23]:
xc1=[1,2,3,4,5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [24]:
xc2=[1; 2; 3; 4; 5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

### We can accessing by one[ i ] and two[ i,j ] subscript

One dimension accessing

In [13]:
xr1[4]

4

In [16]:
xc1[4]

4

In [17]:
xc2[4]

4

Two dimension accessing

In [12]:
xr1[4,1]

4

In [20]:
xc1[1,4]

4

In [21]:
xc2[4,1]

4

# 2. High dimension  arrays

### Matrics

In [32]:
matA=[1 2 3;
      4 5 6; 
      7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [29]:
matAA=matA*matA

3×3 Array{Int64,2}:
  30   36   42
  66   81   96
 102  126  150

In [30]:
matAAinner=matA.*matA

3×3 Array{Int64,2}:
  1   4   9
 16  25  36
 49  64  81

### 3D matrics

In [43]:
matA3D=zeros(Float32,3,3,3)
matA3D[:,:,1]=[1 2 3;
               4 5 6;
               7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [44]:
matA3D[:,:,2]=matA3D[:,:,1].+1

3×3 Array{Float32,2}:
 2.0  3.0   4.0
 5.0  6.0   7.0
 8.0  9.0  10.0

3×3×3 Array{Float32,3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

# 3. Concatanate

### Row concat

In [27]:
xrr=[xr1; xr1]

2×5 Array{Int64,2}:
 1  2  3  4  5
 1  2  3  4  5

### Column concat

In [26]:
xcc=[xc1 xc2]

5×2 Array{Int64,2}:
 1  1
 2  2
 3  3
 4  4
 5  5

# 4. Macro or dot operate

In [25]:
x=1:1:10000

1:1:10000

In [30]:
@time y=cos.(sin.(x))

  0.000196 seconds (7 allocations: 78.359 KiB)


10000-element Array{Float64,1}:
 0.6663667453928805
 0.6143002821164822
 0.9900590857598653
 0.7270351311688124
 0.574400879193934
 0.9612168045072789
 0.7918362090144786
 0.549226270051226
 0.9162743174606308
 0.8556343548213666
 0.5403105467456532
 0.859465627274523
 0.9130208165623314
 ⋮
 0.5788337195354402
 0.9659876821079376
 0.7832902211721673
 0.551621201397961
 0.9229388558089402
 0.8475265310216316
 0.5405243164675815
 0.867406140441677
 0.90605751773827
 0.5462020284401548
 0.8044264629214172
 0.9536622757632013

### Assign value and check length
Preallocating specific length y and assign value using y.= this method will check the input data that have equal length or not. In text book say is faster 

In [34]:
y=zeros(size(x))
@time y.=cos.(sin.(x))

  0.000193 seconds (5 allocations: 160 bytes)


10000-element Array{Float64,1}:
 0.6663667453928805
 0.6143002821164822
 0.9900590857598653
 0.7270351311688124
 0.574400879193934
 0.9612168045072789
 0.7918362090144786
 0.549226270051226
 0.9162743174606308
 0.8556343548213666
 0.5403105467456532
 0.859465627274523
 0.9130208165623314
 ⋮
 0.5788337195354402
 0.9659876821079376
 0.7832902211721673
 0.551621201397961
 0.9229388558089402
 0.8475265310216316
 0.5405243164675815
 0.867406140441677
 0.90605751773827
 0.5462020284401548
 0.8044264629214172
 0.9536622757632013

Protect assigning mismatch size data

In [36]:
x2=[x 1]
y.=cos.(sin.(x))

DimensionMismatch: DimensionMismatch("mismatch in dimension 1 (expected 10000 got 1)")

# 4. Specific Array type